services:
  mongo-1:
    container_name: 'mongo-1-container'
    image: 'mongo:7.0.0'
    entrypoint: /bin/bash /scripts/init-mongo.sh
    ports:
      - "27017:27017"  # Expón el puerto en 0.0.0.0 por defecto
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - 'mongo1data:/data/db'
      - 'mongo1config:/data/configdb'
      - 'sharedconfig:/data'
      - ./scripts:/scripts
    networks:
      - "mynetwork"
    restart: unless-stopped

  mongo-2:
    container_name: 'mongo-2-container'
    image: 'mongo:7.0.0'
    ports:
      - "27018:27017"  # Puerto externo 27018 mapeado al 27017 del contenedor
    volumes:
      - 'mongo2data:/data/db'
      - 'mongo2config:/data/configdb'
      - 'sharedconfig:/data'
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/keyfile.key"]
    networks:
      - "mynetwork"
    restart: unless-stopped

  mongo-3:
    container_name: 'mongo-3-container'
    image: 'mongo:7.0.0'
    ports:
      - "27019:27017"  # Puerto externo 27019 mapeado al 27017 del contenedor
    volumes:
      - 'mongo3data:/data/db'
      - 'mongo3config:/data/configdb'
      - 'sharedconfig:/data'
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/keyfile.key"]
    networks:
      - "mynetwork"
    restart: unless-stopped

volumes:
  mongo1data:
  mongo1config:
  mongo2data:
  mongo2config:
  mongo3data:
  mongo3config:
  sharedconfig:

networks:
  mynetwork:
